### ISSUE TITLE
Mark deprecated features as @Deprecated

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet-jvm#385]
### Feature Request

https://docs.starknet.io/documentation/starknet_versions/deprecated/

We should mark deprecated features and their uses as `@Deprecated`. 

Currently, the list of deprecated features includes GOERLI testnet, declaring Cairo 0 contracts and sending all v1 transactions.

**Comment by gomezmedinamoises** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-jvm).

### My background and how it can be leveraged
I'm mobile developer with 4 years of experience. I'm familiar with Android, Kotlin, Flutter and Dart. For this reason, I'm familiar with the @Deprecated annotation and it's implementation.

### How I plan on tackling this issue
After check documentation above, I know the names and descriptions for required annotations. I just need to check the project in order to see that files are affected for this features and do the required modifications.

If you have some suggestion or consideration about this, feel free to reach out to me via Telegram or GitHub.

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-jvm).

### My background and how it can be leveraged
I’ve developed music player and online food delivery apps using MVVM, Retrofit, Room Database, and Jetpack Compose. Additionally, I’ve completed an internship where I integrated APIs and built advanced UIs with Kotlin and Jetpack Compose, showcasing my ability to create scalable, maintainable, and efficient applications.

### How I plan on tackling this issue

I'll review the codebase to identify uses of the deprecated GOERLI testnet, Cairo 0 contracts, and v1 transactions. Using the @Deprecated annotation in Kotlin, I'll mark these features and suggest alternatives. I'll update the code, conduct thorough testing, and revise documentation to ensure maintainability and compatibility.
