### ISSUE TITLE
Investigate: Sometimes the devnet process remains alive

### ISSUE THREAD

**Issue by bartekryba** [software-mansion/starknet-jvm#95]
When running tests is interrupted, sometimes the devnet process remains alive. It then affects running tests another time.

To do:
* Investigate the cause and fix it, so that the devnet process is killed everytime
* Throw at DevnetClient init, when something is running on its port

**Comment by cptartur** [comment]
Not ideal solution to the problem, but we can mimic starknet.py behavior and try to bind any free port for devnet instead of using fixed values. This way, starting devnet should always succeed. 

It doesn't address the issue of old devnet processes remaining active (maybe they terminate after some time of java program termination, this would require further verification).
